### ISSUE TITLE
save IP address

### ISSUE THREAD

**Issue by veonua** [SmartThingsCommunity/smartthings-cli#208]
**Is your feature request related to a problem? Please describe.**

every time I want to get a log using 
> smartthings edge:drivers:logcat

there is a prompt
> Enter hub IP address with optionally appended port number: 

**Describe the solution you'd like**
it would be great if the app can save this information after a first input. The majority of users have only one hub and the IP address is rather constant.

**Describe alternatives you've considered**

as an alternative, there could be a key for 
edge:drivers:logcat -IP 192.168.0.11

**Comment by john-u** [comment]
@veonua Thanks for reaching out. The `logcat` command does accept a flag `--hub-address` to specify the IP address as seen in the help output of the command or in our [reference here](https://github.com/SmartThingsCommunity/smartthings-cli#smartthings-edgedriverslogcat-driverid). We've found this is handy when combined with shell command history to save it for future runs as you mention.

We are also planning to add automatic hub discovery to this command in a future release so that the local hub can be resolved without explicit input.
