### ISSUE TITLE
Why do I still see "unenrolled" channels and their drivers?

### ISSUE THREAD

**Issue by dmurchie** [SmartThingsCommunity/smartthings-cli#463]
Why do "unenrolled channels" (and their drivers) still appear in the lists with `smartthings edge:channels:drivers`?

I've installed (and then uninstalled) a few different drivers, and after deletion of the drivers I also unenrolled from their channels. Confirmed with `edge:drivers:installed` and `edge:channels:enrollments` (and they don't appear in lists with `edge:drivers:delete` or `edge:channels:delete`).

Maybe I'm missing something? Maybe remembering all channels is by design?

**Comment by rossiam** [comment]
`edge:channels:drivers` lists all drivers assigned to a channel. It does not include any information about hub enrollments to a channel.

If you want to remove a driver from a channel, you can unassign it with `edge:channels:unassign`.

More detail:

* We use the term "assign" for assigning a driver to a channel. A channel is essentially a way to group drivers for sharing.
* We use the term "enroll" for enrolling a hub in a channel. When a hub is enrolled in a channel, drivers assigned to that channel can be installed on the hub. (So in order to install a driver, one needs to assign it to a channel and also enroll the hub in that channel.)

**Comment by dmurchie** [comment]
Thanks for the reply: I understand the "More detail" part and `assign`

The channels prompt list with `edge:channels:driver` is not every channel in the universe, but it does _appear to be_ a mixed list of all channels to which a hub in my ST account is currently enrolled AND other people's channels from which all hubs in my ST account are now unenrolled.

Just curious if anyone knew where/how that list of channels stored? Is there a record of all past interactions with channels held somewhere on my ST account?

Admittedly not an important question - certainly not an "issue" - just curious.

**Comment by orangebucket** [comment]
I think the CLI requests all the channels that you have access to, and that includes any read-only one that you've ever accepted an invitation to even if you really, really don't want to ever see it again. So I've got a test channel from a pull request in my list. There doesn't seem to be a way to uninvite yourself from channels you no longer care about. I find it disproportionately irritating, but the CLI is just the messenger.

**Comment by dmurchie** [comment]
Yeah, "doesn't seem to be a way to uninvite yourself" may be a good description of what's happening (i.e., the list is something different from "enrolled/unenrolled"). Thanks for your reply.
