### ISSUE TITLE
How to display temperature instead of humidity with SONOFF SNZB-02 probes?

### ISSUE THREAD

**Issue by vallieresluc** [SmartThingsCommunity/smartthings-cli#602]
How to display temperature instead of humidity with SONOFF SNZB-02 probes? Currently, the default display in the Smartthings app is humidity. I would like to have the default temperature.

**Additional context**
Add any other context or screenshots about the question here.
![2024-03-16 08 50 58](https://github.com/SmartThingsCommunity/smartthings-cli/assets/99445819/cd42cc52-b4a1-4416-ba48-eff2b2e4add2)

**Comment by Sitlintac** [comment]
This sounds like it might be an issue with your device driver.  Someone on the SmartThings community forum posted a similar issue with their custom driver for the same device a couple of weeks ago ([link](https://community.smartthings.com/t/edge-driver-mc-zigbee-temp-sensor-and-child-thermostat-mc-zigbee-temp-sensor-with-thermostat-mc/234137/601)); you might be able to find a solution to your problem there.  If not, try reaching out to customer support.  Good luck!

**Comment by bsf29** [comment]
I had the same problem with the ST driver.  I have 4 of these SONOFF devices.  Some installed correctly and some were a pain.  I was able to get it to default to temperature by uninstalling & reinstalling.  Sometimes I had to do this several times.  I have since switched to Mariano's edge driver that @Sitlintac mentioned.  The only thing I don't like is that he has a virtual thermostat built into his driver that I don't need.  You don't have to configure/use it and you still get all of the normal temperature & humidity stuff you want.  Mariano also has other edge drivers that I find to be very useful and are worth checking out.

**Comment by Sitlintac** [comment]
This page is specifically for issues for the SmartThings CLI, which doesn't appear to be related to the problem you're having with your SONOFF devices.  I'm sorry to hear that the forum wasn't able to help you solve your problem.  Please try reaching out to customer support for further help.
